project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  favicon: "images/photo.jpg"
  
  page-footer:
    left: |
      [Contact Udval Oyunsaikhan](mailto:udwalamir@gmail.com)
    right: |
      [Github Code Repo](https://github.com/UdvalO)
    background: "#2c3e50"
    
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/UdvalO
      - icon: linkedin
        href: https://www.linkedin.com/in/o-udval/
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-fold: show
    highlight-style: github

